def copy_to_patient(form, patient):
    patient.name = form.name.data
    patient.national_id = form.national_id.data
    patient.hospital_number = form.hospital_number.data
    patient.birth_year = form.birth_year.data
    patient.center_id = form.center_id.data
    patient.gender = form.gender.data
    patient.phone_1 = form.phone_1.data
    patient.phone_1_comments = form.phone_1_comments.data
    patient.phone_2 = form.phone_2.data
    patient.phone_2_comments = form.phone_2_comments.data
    patient.address = form.address.data
